/**
 * Created by breakmetal on 02/01/2015.
 */
//dimensiones y configuracion de pagina
var ancho=window.innerWidth,alto=window.innerHeight
$('#mapa').height(alto *.95);
$('#mapa').width(ancho *.98);
$('#mapa').css({'top':(alto *.08)+'px'})
//cuencas//
var magdalena;
var bogota;
var suarez;
var sumapaz;
var negro;
var cDerecha;
var cArriba;
var isla1
var isla2;
var isla3;
var isla4;
//estaciones
var mag=new Array(4);
var neg=new Array(30);
var sua=new Array(73);
var bog=new Array(174);
var sum=new Array(31);
var cLD=new Array(4);
var cDA=new Array(3);
//estaciones y puntos
var estacionMagdalena=new Array(5);
estacionMagdalena[1]="placer el";
estacionMagdalena[2]="corralitos puli";
estacionMagdalena[3]="corralitos puli";

////////////////////////////////////
var estacionNegro=new Array(32);
estacionNegro[1]="zusne";
estacionNegro[2]="caparrapi";
estacionNegro[3]="Los tiestos";
estacionNegro[4]="boc.acueducto la palma";
estacionNegro[5]="murca";
estacionNegro[6]="puerto leticia";
estacionNegro[7]="puerto leticia";
estacionNegro[8]="puerto guaduero";
estacionNegro[9]="guaduas";
estacionNegro[10]="puente granada";
estacionNegro[11]="san isidro";
estacionNegro[12]="san isidro";
estacionNegro[13]="agua fria";
estacionNegro[14]="paso del rejo(negro)";
estacionNegro[15]="agua fria";
estacionNegro[16]="paso del tigre";
estacionNegro[17]="paso del rejo(negro)";
estacionNegro[18]="puente naranjal";
estacionNegro[19]="salitre blanco";
estacionNegro[20]="puente el";
estacionNegro[21]="puente el";
estacionNegro[22]="viani";
estacionNegro[23]="acomodo el";
estacionNegro[24]="puente cucharal";
estacionNegro[25]="puente arco";
estacionNegro[26]="ferreria la";
estacionNegro[27]="inst. agricola vocacional";
estacionNegro[28]="La Cabrera";
estacionNegro[29]="negrete";
///////////////////////////////
var estacionSuarez=new Array(81);
estacionSuarez[1]="garavito";
estacionSuarez[2]="puente garavito callejon";
estacionSuarez[3]="socotá";
estacionSuarez[4]="esclusa merchan";
estacionSuarez[5]="puente merchan";
estacionSuarez[6]="puente merchan abajo";
estacionSuarez[7]="tolon arriba";
estacionSuarez[8]="esclusa tolon";
estacionSuarez[9]="puente pinilla";
estacionSuarez[10]="florida la";
estacionSuarez[11]="nariño";
estacionSuarez[12]="boqueron el";
estacionSuarez[13]="santa rita";
estacionSuarez[14]="caldas";
estacionSuarez[15]="simijica";
estacionSuarez[16]="arrayanes los";
estacionSuarez[17]="puente san miguel";
estacionSuarez[18]="puente guzman";
estacionSuarez[19]="San Agustín";
estacionSuarez[20]="santa sofia";
estacionSuarez[21]="sutamarchan";
estacionSuarez[22]="central 2";
estacionSuarez[23]="san miguel de sema";
estacionSuarez[24]="chalet norte capellania";
estacionSuarez[25]="chalet norte";
estacionSuarez[26]="calendaria";
estacionSuarez[27]="monasterio";
estacionSuarez[28]="zarzal el";
estacionSuarez[29]="Ticha Muñoz";
estacionSuarez[30]="fuquene ticha maria";
estacionSuarez[31]="puente colorado";
estacionSuarez[32]="puente tichamaria";
estacionSuarez[33]="chizaque";
estacionSuarez[34]="Escuela Guachetá";
estacionSuarez[35]="monserrate";
estacionSuarez[36]="esclusa el clubio";
estacionSuarez[37]="torca";
estacionSuarez[38]="nazareth";
estacionSuarez[39]="tres esquinas";
estacionSuarez[40]="puente el";
estacionSuarez[41]="boqueron el";
estacionSuarez[42]="carupa hospital";
estacionSuarez[43]="malilla";
estacionSuarez[44]="corralejas";
estacionSuarez[45]="represa el hato";
estacionSuarez[46]="deacarga el hato";
estacionSuarez[47]="hato1";
estacionSuarez[48]="pinos los-lag suesca";
estacionSuarez[49]="el hato";
estacionSuarez[50]="hda hato";
estacionSuarez[51]="hato7";
estacionSuarez[52]="hato6";
estacionSuarez[53]="pedregal el";
estacionSuarez[54]="encanto el";
estacionSuarez[55]="puente el pedregal";
estacionSuarez[56]="pinos los-lag suesca";
estacionSuarez[57]="la boyera";
estacionSuarez[58]="captacion1";
estacionSuarez[59]="Boyera-CAR";
estacionSuarez[60]="pino el";
estacionSuarez[61]="triangulo el";
estacionSuarez[62]="palacios";
estacionSuarez[63]="tapias";
estacionSuarez[64]="Puente Cabuya";
estacionSuarez[65]="Captación 2";
estacionSuarez[66]="puente barcelona";
estacionSuarez[67]="media luna";
estacionSuarez[68]="hatillo el";
estacionSuarez[69]="carrizal";
estacionSuarez[70]="espino el";
estacionSuarez[71]="esperanza tibita";
estacionSuarez[72]="triangulo";
//////////////////////////////
var estacionCA=new Array(3);
estacionCA[1]="puente caney";
estacionCA[2]="pinos los";
////////////////////////////
var estacionSumaPaz=new Array(32);
estacionSumaPaz[1]="cairo el";
estacionSumaPaz[2]="puente la panela";
estacionSumaPaz[3]="aguasiso";
estacionSumaPaz[4]="providencia";
estacionSumaPaz[5]="puente la aguadita";
estacionSumaPaz[6]="matadero";
estacionSumaPaz[7]="udec-univ fusagasuga";
estacionSumaPaz[8]="providencia";
estacionSumaPaz[9]="juan XXIII";
estacionSumaPaz[10]="puente rojo";
estacionSumaPaz[11]="pasca";
estacionSumaPaz[12]="pasca1";
estacionSumaPaz[13]="puente caro";
estacionSumaPaz[14]="Puente Los pinos";
estacionSumaPaz[15]="costa rica";
estacionSumaPaz[16]="batan el";
estacionSumaPaz[17]="puente vicente";
estacionSumaPaz[18]="puente rojo";
estacionSumaPaz[19]="puente los rios";
estacionSumaPaz[20]="puente arbelaez";
estacionSumaPaz[21]="pajas blancas";
estacionSumaPaz[22]="pueblo nuevo";
estacionSumaPaz[23]="pajas blancas";
estacionSumaPaz[24]="puente cucharo";
estacionSumaPaz[25]="puente cucharo";
estacionSumaPaz[26]="puente negro";
estacionSumaPaz[27]="puente caracol";
estacionSumaPaz[28]="bocatoma pirineos";
estacionSumaPaz[29]="aguas claras";
estacionSumaPaz[30]="bocatoma venecia";


///////////////////////////////
var estacionBogota=new Array(176);
estacionBogota[1]="la fortuna";
estacionBogota[2]="triunfo el";
estacionBogota[3]="villapinzon";
estacionBogota[4]="villapinzon";
estacionBogota[5]="argentina";
estacionBogota[6]="puente choconta";
estacionBogota[7]="puente choconta";
estacionBogota[8]="saucio";
estacionBogota[9]="saucio pte baraya";
estacionBogota[10]="saucio";
estacionBogota[11]="santa marta";
estacionBogota[12]="puente sisga";
estacionBogota[13]="santa rosita";
estacionBogota[14]="la iberia";
estacionBogota[15]="embalse sisga";
estacionBogota[16]="represa sisga";
estacionBogota[17]="hoyo arriba el";
estacionBogota[18]="puente cacicazgo";
estacionBogota[19]="puente sesquilé";
estacionBogota[20]="iberia la";
estacionBogota[21]="cadillal";
estacionBogota[22]="consuelo el";
estacionBogota[23]="okal el";
estacionBogota[24]="checua";
estacionBogota[25]="puente checua";
estacionBogota[26]="puente florencia";
estacionBogota[27]="puente florencia";
estacionBogota[28]="acandy";
estacionBogota[29]="acequia el molino";
estacionBogota[30]="molino el";
estacionBogota[31]="acequia la quinta";
estacionBogota[32]="bombas sesquilé";
estacionBogota[33]="argelia";
estacionBogota[34]="bolera la";
estacionBogota[35]="carrizal 1";
estacionBogota[36]="guanquica";
estacionBogota[37]="ladera grande";
estacionBogota[38]="llano el";
estacionBogota[39]="barrancas";
estacionBogota[40]="salitre el";
estacionBogota[41]="volador el";
estacionBogota[42]="represa neusa";
estacionBogota[43]="canaleta parshall";
estacionBogota[44]="paramo del guerrero";
estacionBogota[45]="venta larga";
estacionBogota[46]="el recreo";/////
estacionBogota[47]="la pradera";
estacionBogota[48]="manzano el";
estacionBogota[49]="el cedral";
estacionBogota[50]="ave colombiana";
estacionBogota[51]="rodamontal";
estacionBogota[52]="zipaquira";
estacionBogota[53]="espino el";
estacionBogota[54]="panaca";
estacionBogota[55]="pte tocancipá";
estacionBogota[56]="pte tocancipá";
estacionBogota[57]="puente vargas";
estacionBogota[58]="guatativa";
estacionBogota[59]="montecillos";
estacionBogota[60]="La María";
estacionBogota[61]="san jose";
estacionBogota[62]="santodomingo";
estacionBogota[63]="vergel el";
estacionBogota[64]="vergel el";
estacionBogota[65]="puente adobes";
estacionBogota[66]="parque sopo";
estacionBogota[67]="puente vargas";
estacionBogota[68]="univ nueva granada";
estacionBogota[69]="alco";
estacionBogota[70]="paso ancho";
estacionBogota[71]="pozo hondo";
estacionBogota[72]="planadas";
estacionBogota[73]="guamal";
estacionBogota[74]="santa isabel";
estacionBogota[75]="puente calamar";
estacionBogota[76]="pradera la";
estacionBogota[77]="puente calamar";
estacionBogota[78]="potrero el";
estacionBogota[79]="la vega";
estacionBogota[80]="la esperanza";
estacionBogota[81]="las mercedes";
estacionBogota[82]="villa paula";
estacionBogota[83]="puente manrique";
estacionBogota[84]="puente cacique";
estacionBogota[85]="La Balsa Chía";
estacionBogota[86]="Apto Guaimaral- USTA";
estacionBogota[87]="santa teresa";
estacionBogota[88]="simaya";
estacionBogota[89]="puente la calera";
estacionBogota[90]="torca";
estacionBogota[91]="puente la virgen";
estacionBogota[92]="santa ines";
estacionBogota[93]="acequia san patricio";
estacionBogota[94]="muralla la";
estacionBogota[95]="chicu el bogota";
estacionBogota[96]="puente cundinamarca";
estacionBogota[97]="casita la";
estacionBogota[98]="edificio car";
estacionBogota[99]="bosque el";
estacionBogota[100]="primavera la";
estacionBogota[101]="union la";
estacionBogota[102]="margaritas las";
estacionBogota[103]="ramada la";
estacionBogota[104]="puente cundinamaarca";
estacionBogota[105]="campobello";
estacionBogota[106]="altamira";
estacionBogota[107]="hacienda virginia";
estacionBogota[108]="triibuna la";
estacionBogota[109]="hacienda grande";
estacionBogota[110]="venecia";
estacionBogota[111]="rebose gatillo";
estacionBogota[112]="bojaca";
estacionBogota[113]="puente ferrocarril";
estacionBogota[114]="cartagena";
estacionBogota[115]="cachipay";
estacionBogota[116]="prosocial";
estacionBogota[117]="pedro palo";
estacionBogota[118]="pedro palo";
estacionBogota[119]="esperanza la";
estacionBogota[120]="peña negra";
estacionBogota[121]="manzanares";
estacionBogota[122]="san javier";
estacionBogota[123]="mesa la";
estacionBogota[124]="san gregorio";
estacionBogota[125]="puente carretera";
estacionBogota[126]="puente lutaima";
estacionBogota[127]="violetas las";
estacionBogota[128]="dario valencia";
estacionBogota[129]="anclaje14";
estacionBogota[130]="monterrey";
estacionBogota[131]="montuañela";
estacionBogota[132]="boquemonte";
estacionBogota[133]="El Fute";
estacionBogota[134]="huertas las";
estacionBogota[135]="la campiña";
estacionBogota[136]="tribuna la";
estacionBogota[137]="sibate apostolica";
estacionBogota[138]="hungria";
estacionBogota[139]="san jorge granja";
estacionBogota[140]="doña juana";
estacionBogota[141]="tesoro";
estacionBogota[142]="El Bosque Cisaca";
estacionBogota[143]="villa blanca";
estacionBogota[144]="paraiso perdido";
estacionBogota[145]="torres";
estacionBogota[146]="peñas blancas";
estacionBogota[147]="escuela antioquia";
estacionBogota[148]="victoria la";
estacionBogota[149]="delirio el";
estacionBogota[150]="el triunfo";
estacionBogota[151]="java";
estacionBogota[152]="san pabluna";
estacionBogota[153]="cascada la";
estacionBogota[154]="america";
estacionBogota[155]="laguna el indio";
estacionBogota[156]="pola la";
estacionBogota[157]="puerto brasil la mona";
estacionBogota[158]="puerto brasil ruisito";
estacionBogota[159]="entrerios";
estacionBogota[160]="viota";
estacionBogota[161]="neptuna la";
estacionBogota[162]="caracoli";
estacionBogota[163]="granja bosconia";
estacionBogota[164]="pueblo de piedra";
estacionBogota[165]="puente samper madrid";
estacionBogota[166]="puente saenz";
estacionBogota[167]="granja bosconia";
estacionBogota[168]="apulo";
estacionBogota[169]="puente apulo";
estacionBogota[170]="victoria la";
estacionBogota[171]="portillo el";
estacionBogota[172]="tocaima";
estacionBogota[173]="silencio el";


/////////////////////////////
var estacionCD=new Array(4);
estacionCD[1]="el molino"
estacionCD[2]="las gaviotas"
estacionCD[3]="agua blanca"
estacionCD[4]="manta";









